#!/usr/bin/env python3

import sys
import re
import json

src = open(sys.argv[1], 'r').read()

tokens = src.split()

class Point:
    def __init__(self, lon, lat):
        self.lon = lon
        self.lat = lat

    def resolve(self, point):
        pass

    def to_geojson(self):
        pass

    def distance_to(self, point):
        pass

    def __add__(self, point):
        lon = self.lon + point.lon
        lat = self.lat + point.lat
        return Point(lon, lat)

    def __str__(self):
        return '(' + self.lon + ',' + self.lat + ')'

class Rect:
    def __init__(self, points):
        self.points = points

class Parser:
    @staticmethod
    def parse_point(p_str):
        p = re.sub('[\(\)]', '', p_str).split(',')
        return Point(p[0], p[1])

if tokens[0] == 'rect':
    p1 = Parser.parse_point(tokens[1])
    p2 = Parser.parse_point(tokens[2])
    r = Rect([p1, p2])
    feature = {}
    feature['type'] = 'Polygon'

    print(json.dumps(feature))
